on:
  push:
    branches: [$default-branch]
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install package.json dependencies
        run: npm install
      - name: Build site
        run: npm run build
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Create artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
      